---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: mariadb

images:
  - name: mariadb-server
    newName: library/mariadb
    newTag: "10"

...
