---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: mariadb-passwd
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: passwd

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-passwd

subjects:
  - kind: ServiceAccount
    name: mariadb-passwd

...
