---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: mariadb-passwd
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: passwd

rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "list"
      - "create"
      - "get"
      - "patch"

...
