---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: mariadb-config
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-init
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-server
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals:
      - MARIADB_DATABASE=test

secretGenerator:
  - name: mariadb-admin
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files: []
  - name: mariadb-user
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files: []

...
