---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: mariadb-config
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-init
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-server
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals:
      - MARIADB_DATABASE=test
  - name: mariadb-metrics
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []

secretGenerator:
  - name: mariadb-admin
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files: []
  - name: mariadb-user
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files: []

images:
  - name: mariadb-server
    newName: library/mariadb
    newTag: "10.11.3"
  - name: mariadb-metrics
    newName: prom/mysqld-exporter
    newTag: "v0.14.0"

...
